### ISSUE TITLE
Freeze the top row of the table with the labels to make it easier to read when scrolling

### ISSUE THREAD

**Issue by vorburger** [filecoin-saturn/L1-dashboard#12]
I am a noob and I find myself frequently scrolling up and down on https://orchestrator.strn.pl/stats to remember which column is which.

It could be neat if the top row with the labels could be fixed & frozen when you scroll.

**Comment by guanzo** [comment]
I have the same issue.

@kwypchlo hopefully the new datatable UI includes sticky headers?

**Comment by interstella-5555** [comment]
> I have the same issue.
> 
> @kwypchlo hopefully the new datatable UI includes sticky headers?

Yes it does :) I will take care of referencing all those resolved issues when we merge.
