### ISSUE TITLE
migrate from s3 to a web3 host

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-dashboard#15]
just to drink more web3 koolaid ourselves. potential 'web3' hosts could be fleek or other

this is not currently a high priority

**Comment by interstella-5555** [comment]
for fleek, we should wait until they update their gateway to support https://docs.ipfs.tech/how-to/websites-on-ipfs/redirects-and-custom-404s/

I posted a request for that on their discord to see if I can get any traction

**Comment by interstella-5555** [comment]
https://dashboard.strn.network/ is now being served from ipfs through fleek.co (deployed from main branch)

how? configuration for CNAME `dashboard.strn.network` has been changed on our [cloudflare](https://www.cloudflare.com/) account from `d3r00wmlwgxp67.cloudfront.net` to `b0cac29553481fefb931.b-cdn.net` as per [fleek.co domain configuration](https://app.fleek.co/#/sites/dashboard-strn/settings/domain-management?accountId=6b76ddc3-e5e2-4cee-92cd-a66ecabe35ec).
