### ISSUE TITLE
selecting a node doesn't load that node's stats in the overview panel

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-dashboard#40]
to reproduce:
1. load https://dashboard.saturn.tech/address/all?period=7+Days
2. click on an individual node
![image](https://user-images.githubusercontent.com/1041265/234983083-21b735e7-4659-41b7-8771-35a49324f511.png)
3. the earnings, retrievals, and bandwidth served graphs update correctly
4. but the overview panel does not and still shows aggregate stats, not stats for the node that was just selected
![image](https://user-images.githubusercontent.com/1041265/234983283-4902e10e-69e9-4b60-b0cb-3cf4fccb0221.png)

note: the current dashboard UI will be change significantly by https://github.com/filecoin-saturn/L1-dashboard/issues/38, but the same bug would persist there and thus should be solved

**Comment by AmeanAsad** [comment]
Resolved in: https://github.com/filecoin-saturn/L1-dashboard/pull/41
