### ISSUE TITLE
Website vs. embedded web

### ISSUE THREAD

**Issue by bajtos** [filecoin-saturn/L1-dashboard#5]
We need to support two runtime modes:

- a website served at [https://dashboard.strn.network/](https://dashboard.strn.network/)
- an embedded WebUI served by Saturn L2 node

When running as a website:
- We need the user to enter their FIL wallet address.
- We don't have access to metrics API provided by the local Saturn node.

When running embedded inside Saturn node:
- We should hide the FIL address configuration. The address is provided by the node.
- We can show additional details and metrics, as provided by the Saturn node.

See also https://github.com/filecoin-project/saturn-webui/issues/5

**Comment by guanzo** [comment]
> We should hide the FIL address configuration. The address is provided by the node.

Filecoin station can just load the webui at `/webui/address/<address>` instead of the root, which will skip the FIL address form page.

**Comment by bajtos** [comment]
> Filecoin station can just load the webui at `/webui/address/<address>` instead of the root, which will skip the FIL address form page.

Makes sense.

I also need to hide the FIL address input element on the dashboard page.

**Comment by guanzo** [comment]
Gotcha. Yeah I think we just hide the navbar itself, which consists of the saturn logo and the input element.

As for the additional metrics, if they're just rendered as charts then we can append/prepend them to the chart container. Hard to say how to update the UI until I know what the additional details/metrics are.
